# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../multiple_flutters_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'MultiEnginesIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
  # pod 'GoogleMaps', '9.1.1'
  # Pods for MultiEnginesIOS
  require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
  install_flutter_plugin_pods(flutter_application_path)

  target 'MultiEnginesIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultiEnginesIOSUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end